name: Build resume

on:
  push:
    tags:
      - 'v*'   # Only trigger release job on version tags
    branches:
      - main   # Still build on main pushes

jobs:
  build-resume:
    runs-on: ubuntu-22.04
    name: Build resume artifacts

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build resume
        uses: ./
        with:
          theme-package-url: 'https://github.com/rizwan-kh/jsonresume-theme-helloquan/releases/download/v4.5.4/jsonresume-theme-hellokhan-4.5.2.tgz'

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: resume-artifacts
          path: |
            resume.html
            resume.pdf

  release-resume:
    if: startsWith(github.ref, 'refs/tags/')
    needs: build-resume
    runs-on: ubuntu-22.04
    name: Release and publish resume

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: resume-artifacts

      - name: Generate artifact name
        id: vars
        run: echo "artifact_name=rizwan-kh-resume-${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Create or update GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          name: Release ${{ github.ref_name }}
          tag_name: ${{ github.ref_name }}
          body: |
            Changes in this Release
            - Trial
          files: |
            resume.html
            resume.pdf
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Prepare public directory
        run: |
          mkdir public
          cp resume.html public/index.html

      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: gh-pages
          build_dir: public
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
