name: Publish Docker image
on: 
  [push]

jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-20.04
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: docker.pkg.github.com
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push to GitHub Container Registry
        uses: docker/build-push-action@v2
        with:
          push: true # Will only build if this is not here
          tags: |
            docker.pkg.github.com/${{ github.repository }}/resume-builder:${{ github.sha }}
            docker.pkg.github.com/${{ github.repository }}/resume-builder:latest
